# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\x07Request\x12\x11\n\tclient_id\x18\x01 \x01(\x03\x12\x14\n\x0crequest_data\x18\x02 \x01(\t\"4\n\x08Response\x12\x11\n\tserver_id\x18\x01 \x01(\x03\x12\x15\n\rresponse_data\x18\x02 \x01(\t2I\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x32\xa0\x02\n\x08GRPCDemo\x12\x39\n\x0cSimpleMethod\x12\x13.helloworld.Request\x1a\x14.helloworld.Response\x12\x44\n\x15\x43lientStreamingMethod\x12\x13.helloworld.Request\x1a\x14.helloworld.Response(\x01\x12\x44\n\x15ServerStreamingMethod\x12\x13.helloworld.Request\x1a\x14.helloworld.Response0\x01\x12M\n\x1c\x42idirectionalStreamingMethod\x12\x13.helloworld.Request\x1a\x14.helloworld.Response(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=32
  _globals['_HELLOREQUEST']._serialized_end=60
  _globals['_HELLOREPLY']._serialized_start=62
  _globals['_HELLOREPLY']._serialized_end=91
  _globals['_REQUEST']._serialized_start=93
  _globals['_REQUEST']._serialized_end=143
  _globals['_RESPONSE']._serialized_start=145
  _globals['_RESPONSE']._serialized_end=197
  _globals['_GREETER']._serialized_start=199
  _globals['_GREETER']._serialized_end=272
  _globals['_GRPCDEMO']._serialized_start=275
  _globals['_GRPCDEMO']._serialized_end=563
# @@protoc_insertion_point(module_scope)
